#!/usr/bin/env python3
"""
把 runtime.lua 转成 C 可包含的字节数组头文件。

输出形如：
    static const unsigned char runtime_lua_blob[] = { 0x2D, 0x2D, ... };
    static const unsigned int  runtime_lua_blob_len = 1234;

供 jni/easylua.c 中 luaL_loadbuffer 使用。
"""
import sys
from pathlib import Path


def main(src: str, dst: str):
    data = Path(src).read_bytes()
    out = []
    out.append("/* AUTO-GENERATED by embed_lua.py — DO NOT EDIT */")
    out.append("/* source: jni/runtime.lua */")
    out.append("#pragma once")
    out.append("")
    out.append(f"static const unsigned int runtime_lua_blob_len = {len(data)};")
    out.append("static const unsigned char runtime_lua_blob[] = {")
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        line = "    " + ", ".join(f"0x{b:02X}" for b in chunk) + ","
        out.append(line)
    # 删掉最后一个多余逗号没必要，C 允许结尾逗号
    out.append("};")
    out.append("")
    Path(dst).write_text("\n".join(out), encoding="utf-8")
    print(f"[+] embedded {len(data)} bytes -> {dst}")


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) >= 2 else "jni/runtime.lua"
    dst = sys.argv[2] if len(sys.argv) >= 3 else "jni/runtime_lua.h"
    main(src, dst)
